//! The fields that can be used in queries.
//!
//! Some field types can be used for multiple entities, to make it more user
//! friendly the types are reexported to the submodules corresponding to the
//! names of the entities which they can be used to query.
//!
//! Link to [MusicBrainz
//! documentation](https://musicbrainz.org/doc/Indexed_Search_Syntax).

use crate::error::{Error, ErrorKind};
use crate::entities as full_entities;
use crate::entities::{Mbid, PartialDate, Resource};
use std::fmt;

fn wrong_search_field(entity: &str, field: &str) -> Error {
    Error::new(
        format!(
            "Requested field {} of entity {}, but this is not provided.",
            field, entity
        ),
        ErrorKind::UsageError,
    )
}

pub trait SearchField {
    type Value;

    fn name<R: Resource>(&self) -> Result<&'static str, Error>;
    fn value(&self) -> String;

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/////////////////////////////////////////////////////////////////
// Don't edit the code below this line as it is autogenerated. //
/////////////////////////////////////////////////////////////////

// BEGIN CODEGEN(searchfields)
/// Alias of the entity's name.
pub struct Alias(pub String);

impl SearchField for Alias {
    type Value = String;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("alias"),
            full_entities::Artist::NAME => Ok("alias"),
            s => Err(wrong_search_field(R::NAME, "Alias")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// The MBID of the Area
pub struct AreaMbid(pub Mbid);

impl SearchField for AreaMbid {
    type Value = Mbid;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("aid"),
            s => Err(wrong_search_field(R::NAME, "AreaMbid")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// An ISO 3166-1/2/3 code attached to the `Area`.
pub struct AreaIso(pub String);

impl SearchField for AreaIso {
    type Value = String;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("iso"),
            s => Err(wrong_search_field(R::NAME, "AreaIso")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// The type of the Area.
pub struct AreaType(pub full_entities::AreaType);

impl SearchField for AreaType {
    type Value = full_entities::AreaType;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("type"),
            s => Err(wrong_search_field(R::NAME, "AreaType")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// TODO: docstring
pub struct BeginArea(pub String);

impl SearchField for BeginArea {
    type Value = String;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Artist::NAME => Ok("begin_area"),
            s => Err(wrong_search_field(R::NAME, "BeginArea")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// Begin date of the entity, this can have a different interpretation depending on the searched entity.
pub struct BeginDate(pub PartialDate);

impl SearchField for BeginDate {
    type Value = PartialDate;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("begin"),
            full_entities::Artist::NAME => Ok("begin"),
            s => Err(wrong_search_field(R::NAME, "BeginDate")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// Disambiguation comment of the searched entity.
pub struct Comment(pub String);

impl SearchField for Comment {
    type Value = String;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::Area::NAME => Ok("comment"),
            full_entities::Artist::NAME => Ok("comment"),
            full_entities::Release::NAME => Ok("comment"),
            full_entities::ReleaseGroup::NAME => Ok("comment"),
            s => Err(wrong_search_field(R::NAME, "Comment")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// The name of the release group.
pub struct ReleaseGroupName(pub String);

impl SearchField for ReleaseGroupName {
    type Value = String;

    fn name<R: Resource>(&self) -> Result<&'static str, Error> {
        match R::NAME {
            full_entities::ReleaseGroup::NAME => Ok("releasegroup"),
            s => Err(wrong_search_field(R::NAME, "ReleaseGroupName")),
        }
    }

    fn value(&self) -> String {
        format!("{}", self.0)
    }

    fn to_string<R: Resource>(&self) -> Result<String, Error> {
        Ok(format!("{}:{}", self.name::<R>()?, self.value()))
    }
}

/// Search fields for Area entities.
pub mod area {
    pub use super::Alias;
    pub use super::AreaMbid;
    pub use super::AreaIso;
    pub use super::AreaType;
    pub use super::BeginDate;
    pub use super::Comment;
}

/// Search fields for Artist entities.
pub mod artist {
    pub use super::Alias;
    pub use super::BeginArea;
    pub use super::BeginDate;
    pub use super::Comment;
}

/// Search fields for Release entities.
pub mod release {
    pub use super::Comment;
}

/// Search fields for ReleaseGroup entities.
pub mod release_group {
    pub use super::Comment;
    pub use super::ReleaseGroupName;
}
// END CODEGEN(searchfields)

/*


// TODO consider whether we should rename `Comment` to `Disambiguation` or
// something like that to
// be more consistent with the rest of the crate.
//
// TODO: enums for quality, script, etc
// TODO it's a bit ugly we have `-` at the beginning of every line but its a
// workaround around the parsing ambiguity we'd have if we didn't.
define_fields!(


    /// An ISO 3166-1 code attached to the `Area`.
    - AreaIso1, String;
    /// An ISO 3166-2 code attached to the `Area`.
    - AreaIso2, String;
    /// An ISO 3166-3 code attached to the `Area`.
    - AreaIso3, String;
    - ArtistCredit, String;
    /// The MBID of the `Artist`.
    - ArtistMbid, Mbid;
    /// The name of the `Artist` without accented characters.
    - ArtistName, String;
    /// The name of the `Artist` with accented characters.
    - ArtistNameAccent, String;
    /// The type of the `Artist`.
    - ArtistType, full_entities::ArtistType;
    - Asin, String;
    /// The barcode of a `Release`.
    - Barcode, String;

    - CatalogNumber, String;
    - Country, String;
    - CreditName, String;
    - DataQuality, String;
    - EndArea, String;
    /// End date of the searched entity.
    ///
    /// Check the searched entity's documentation for more information what this means concretely.
    - EndDate, PartialDate;
    /// Whether the searched entity has already ended.
    ///
    /// Check the searched entity's documentation for more information what this means concretely.
    - Ended, bool;
    /// The gender of an `Artist`.
    - Gender, String;
    - IpiCode, String;
    - LabelId, String;
    - Language, full_entities::Language;
    - MediumCount, u32;
    - MediumFormat, String;
    /// The searched entity's name. (TODO implement for all relevant searches)
    - Name, String;
    - NumDiscIds, u32;
    - NumDiscIdsMedium, u32;
    - NumTracks, u32;
    - NumTracksMedium, u32;
    - PrimaryType, full_entities::ReleaseGroupPrimaryType;
    - ReleaseDate, full_entities::PartialDate;
    - ReleaseGroupId, Mbid;
    - ReleaseGroupNameAccent, String;
    - ReleaseId, Mbid;
    /// The name of the `Release`, without special accent characters.
    - ReleaseName, String;
    /// The name of the `Release`, including special accent characters.
    - ReleaseNameAccent, String;
    - ReleaseNumber, u16;
    - ReleaseStatus, full_entities::ReleaseStatus;
    - Script, String;
    - SecondaryType, String;
    /// The sort name of the searched entity.
    - SortName, String;
    - Tag, String
);

macro_rules! define_entity_fields {
    (
        $field_trait:ident, $modname:ident;
        $(
             $strname:expr, $field_type:ident
        );*
        ;
    )
        =>
    {
        /// Acceptable fields searching for instances of the entity.
        pub trait $field_trait : SearchField {
            fn name() -> &'static str;
        }

        pub mod $modname {
            pub use super::$field_trait;

            $(
                pub use super::$field_type;

                impl $field_trait for $field_type {
                    fn name() -> &'static str { $strname }
                }
            )*
        }

    }
}

define_entity_fields!(
    AreaSearchField, area;

    "aid", AreaMbid;
    "alias", Alias;
    "area", AreaName;
    "area", Name;
    "begin", BeginDate;
    "comment", Comment;
    "end", EndDate;
    "ended", Ended;
    "iso", AreaIso;
    "iso1", AreaIso1;
    "iso2", AreaIso2;
    "iso3", AreaIso3;
    "sortname", SortName;
    "type", AreaType;
);

define_entity_fields!(
    ArtistSearchField, artist;

    "area", AreaName;
    "arid", ArtistMbid;
    "artist", ArtistName;
    "artistaccent", ArtistNameAccent;
    "country", Country;
    "end", EndDate;
    "endarea", EndArea;
    "ended", Ended;
    "gender", Gender;
    "ipi", IpiCode;
    "sortname", SortName;
    "tag", Tag;
    "type", ArtistType;
);

// TODO what are puids?
define_entity_fields!(
    ReleaseSearchField, release;

    "arid", ArtistMbid;
    "artist", ArtistName;
    "asin", Asin;
    "barcode", Barcode;
    "catno", CatalogNumber;
    "country", Country;
    "creditname", CreditName;
    "date", ReleaseDate;
    "discids", NumDiscIds;
    "discidsmedium", NumDiscIdsMedium;
    "format", MediumFormat;
    "laid", LabelId;
    "lang", Language;
    "mediums", MediumCount;
    "primarytype", PrimaryType;
    "quality", DataQuality;
    "reid", ReleaseId;
    "release", ReleaseName;
    "releaseaccent", ReleaseNameAccent;
    "rgid", ReleaseGroupId;
    "script", Script;
    "secondarytype", SecondaryType;
    "status", ReleaseStatus;
    "tag", Tag;
    "tracks", NumTracks;
    "tracksmedium", NumTracksMedium;
);

define_entity_fields!(
    ReleaseGroupSearchField, release_group;

    "arid", ArtistMbid;
    "artist", ArtistCredit;
    "artistname", ArtistName;
    "comment", Comment;
    "creditname", CreditName;
    "primarytype", PrimaryType;
    "reid", ReleaseId;
    "release", ReleaseName;
    "releasegroupaccent", ReleaseGroupNameAccent;
    "releases", ReleaseNumber;
    "rgid", ReleaseGroupId;
    "secondarytype", SecondaryType;
    "status", ReleaseStatus;
    "tag", Tag;
);
*/
